{
	"version": 1593438172,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/untitled1_0000s_0001_11_-sheet0.png",
		"images/backround-sheet0.png",
		"images/backround-sheet1.png",
		"images/backround-sheet2.png",
		"images/backround-sheet3.png",
		"images/backround-sheet4.png",
		"images/spawn1-sheet0.png",
		"images/untitled1_0013_selamatpagisayangku-sheet0.png",
		"images/float1-sheet0.png",
		"images/float1-sheet1.png",
		"images/float2-sheet0.png",
		"images/float2-sheet1.png",
		"images/float3-sheet0.png",
		"images/float3-sheet1.png",
		"images/float4-sheet0.png",
		"images/float4-sheet1.png",
		"images/untitled1_0012_semangat-sheet0.png",
		"images/untitled1_0010_holaaaaa_ow_-sheet0.png",
		"images/screenshot-sheet0.png",
		"images/untitled1_0004_layer-sheet0.png",
		"images/untitled1_0004_layer-sheet1.png",
		"images/untitled1_0011_pagiisayangkubangunnnmandisarapanselamatmemulaihar-sheet0.png",
		"images/untitled1_0011_pagiisayangkubangunnnmandisarapanselamatmemulaihar-sheet1.png",
		"images/love-sheet0.png",
		"images/star-sheet0.png",
		"files/y2mate.com - plop! sound effect original - mougame_cdtwkfjwsy8.ogg",
		"files/y2mate.com - frad - first date_avk0bivqllc.ogg",
		"files/y2mate.com - Ｆｉｒｓｔ Ｄａｔｅ(daycoreanti-nightcoreslowed down)_17xj0j_fp8c.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}